__title__ = "llama-jarvis"
__version__ = "0.1.0"
__description__ = "Train a speech-to-speech model using your own language model"
__author__ = "John Sutor"
__author_email__ = "johnsutor3@gmail.com"
__license__ = "MIT" 
__url__ = "https://github.com/johnsutor/llama-jarvis"